######################################################################
# Automatically generated by qmake (2.01a) Thu 4. Oct 09:57:15 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml phonon

CONFIG += CONSOLE

# Input
HEADERS += ttimer.h
SOURCES += main.cpp ttimer.cpp
